/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coderbd.lms.view;

import com.coderbd.lms.domain.Author;
import com.coderbd.lms.domain.Book;
import com.coderbd.lms.domain.BookCategory;
import com.coderbd.lms.domain.BookSummary;
import com.coderbd.lms.domain.Edition;
import com.coderbd.lms.domain.Publisher;
import com.coderbd.lms.service.AuthorService;
import com.coderbd.lms.service.BookCategoryService;
import com.coderbd.lms.service.BookService;
import com.coderbd.lms.service.BookSummaryService;
import com.coderbd.lms.service.EditionService;
import com.coderbd.lms.service.PublisherService;
import java.util.List;
import java.util.Set;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Rajail Islam
 */
public class LmsPurchaseBook extends javax.swing.JFrame {

    Book book;
    BookService bookService;
    BookSummaryService bookSummaryService;

    /**
     * Creates new form LmsDashboard
     */
    public LmsPurchaseBook() {
        initComponents();
        displayBookWithinTable();
        showAuthorIdInTable();
        showPublisherInTable();
        showEditionInTable();
        showCategoryInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBookName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBookCode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtxUnitPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRackNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtIssuNo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblShowBookInformation = new javax.swing.JTable();
        comboAuthorName = new javax.swing.JComboBox<>();
        comboPublisherName = new javax.swing.JComboBox<>();
        comboEditionName = new javax.swing.JComboBox<>();
        comboCategoryName = new javax.swing.JComboBox<>();
        comboDay = new javax.swing.JComboBox<>();
        comboMonth = new javax.swing.JComboBox<>();
        comboYear = new javax.swing.JComboBox<>();
        menuBar = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        mnAuthor = new javax.swing.JMenuItem();
        mnBookCategory = new javax.swing.JMenuItem();
        mnPurchaseBook = new javax.swing.JMenuItem();
        mnBookIssue = new javax.swing.JMenuItem();
        mnBookReceive = new javax.swing.JMenuItem();
        mnBookSummary = new javax.swing.JMenuItem();
        mnDepartment = new javax.swing.JMenuItem();
        mnEdition = new javax.swing.JMenuItem();
        mnInstitute = new javax.swing.JMenuItem();
        mnPublisher = new javax.swing.JMenuItem();
        mnSesson = new javax.swing.JMenuItem();
        mnShift = new javax.swing.JMenuItem();
        mnStudent = new javax.swing.JMenuItem();
        mnUser = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        mnLogout3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Purchase Book | Library Management System");
        setBackground(new java.awt.Color(255, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Library Management System");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51), 2));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("2017-18 All Rights Reserved. Library Management System");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 51));
        jLabel3.setText("Submit Purchase Book");

        jLabel4.setText("Name:");

        txtBookName.setToolTipText("");

        jLabel5.setText("Book Code:");

        txtBookCode.setToolTipText("");

        jLabel6.setText("Author Name:");

        jLabel7.setText("Publisler:");

        jLabel8.setText("Edition:");

        jLabel10.setText("Unit Price:");

        txtxUnitPrice.setToolTipText("");

        jLabel9.setText("Qty:");

        txtQty.setToolTipText("");

        jLabel11.setText("Total Price:");

        txtTotalPrice.setToolTipText("");

        jLabel12.setText("Rack No:");

        txtRackNo.setToolTipText("");

        jLabel13.setText("Issu No:");

        txtIssuNo.setToolTipText("");

        jLabel14.setText("Category:");

        jLabel15.setText("Purchase date:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(0, 204, 51));

        tblShowBookInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Book Code:", "Author Name:", "Publisler", "Edition", "Unit Price", "Qty", "Total Price", "Rack No", "Issu No", "Category", "Purchase date"
            }
        ));
        tblShowBookInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblShowBookInformationMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblShowBookInformation);

        comboAuthorName.setEditable(true);

        comboPublisherName.setEditable(true);

        comboEditionName.setEditable(true);

        comboCategoryName.setEditable(true);

        comboDay.setEditable(true);
        comboDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        comboMonth.setEditable(true);
        comboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        comboYear.setEditable(true);
        comboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2015", "2016", "2017", "2018", "2019", "2020" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel4))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQty)
                                    .addComponent(txtxUnitPrice)
                                    .addComponent(txtBookCode)
                                    .addComponent(txtBookName)
                                    .addComponent(txtTotalPrice)
                                    .addComponent(txtRackNo)
                                    .addComponent(txtIssuNo)
                                    .addComponent(comboAuthorName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboPublisherName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboEditionName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboCategoryName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboDay, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnAdd))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBookCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(comboAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(comboPublisherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(comboEditionName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtxUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRackNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIssuNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(comboCategoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(comboDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)
                        .addGap(114, 114, 114))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))))
        );

        jMenu4.setText("File");

        mnAuthor.setText("Author");
        mnAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAuthorActionPerformed(evt);
            }
        });
        jMenu4.add(mnAuthor);

        mnBookCategory.setText("Book Category");
        mnBookCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBookCategoryActionPerformed(evt);
            }
        });
        jMenu4.add(mnBookCategory);

        mnPurchaseBook.setText("Purchase Book");
        mnPurchaseBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPurchaseBookActionPerformed(evt);
            }
        });
        jMenu4.add(mnPurchaseBook);

        mnBookIssue.setText("Book Issue ");
        mnBookIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBookIssueActionPerformed(evt);
            }
        });
        jMenu4.add(mnBookIssue);

        mnBookReceive.setText("Book Receive");
        mnBookReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBookReceiveActionPerformed(evt);
            }
        });
        jMenu4.add(mnBookReceive);

        mnBookSummary.setText("Book Summary");
        mnBookSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBookSummaryActionPerformed(evt);
            }
        });
        jMenu4.add(mnBookSummary);

        mnDepartment.setText("Department");
        mnDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDepartmentActionPerformed(evt);
            }
        });
        jMenu4.add(mnDepartment);

        mnEdition.setText("Edition");
        mnEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEditionActionPerformed(evt);
            }
        });
        jMenu4.add(mnEdition);

        mnInstitute.setText("Institute");
        mnInstitute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnInstituteActionPerformed(evt);
            }
        });
        jMenu4.add(mnInstitute);

        mnPublisher.setText("Publisher");
        mnPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPublisherActionPerformed(evt);
            }
        });
        jMenu4.add(mnPublisher);

        mnSesson.setText("Sesson");
        mnSesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSessonActionPerformed(evt);
            }
        });
        jMenu4.add(mnSesson);

        mnShift.setText("Shift");
        mnShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnShiftActionPerformed(evt);
            }
        });
        jMenu4.add(mnShift);

        mnStudent.setText("Student");
        mnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnStudentActionPerformed(evt);
            }
        });
        jMenu4.add(mnStudent);

        mnUser.setText("User");
        mnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUserActionPerformed(evt);
            }
        });
        jMenu4.add(mnUser);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu4.add(mnExit);

        menuBar.add(jMenu4);

        mnHelp.setText("Help");
        menuBar.add(mnHelp);

        mnLogout3.setText("Dash Board");
        mnLogout3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnLogout3MouseClicked(evt);
            }
        });
        menuBar.add(mnLogout3);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnBookCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBookCategoryActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(true);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnBookCategoryActionPerformed

    private void mnAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAuthorActionPerformed
        this.setVisible(false);

        new LmsAuthor().setVisible(true);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnAuthorActionPerformed

    private void mnPurchaseBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPurchaseBookActionPerformed
        this.setVisible(false);

        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
         new LmsPurchaseBook().setVisible(true);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnPurchaseBookActionPerformed

    private void mnBookIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBookIssueActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(true);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnBookIssueActionPerformed

    private void mnBookReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBookReceiveActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(true);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnBookReceiveActionPerformed

    private void mnBookSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBookSummaryActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(true);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnBookSummaryActionPerformed

    private void mnDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDepartmentActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(true);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnDepartmentActionPerformed

    private void mnEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEditionActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(true);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnEditionActionPerformed

    private void mnInstituteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnInstituteActionPerformed

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(true);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);

    }//GEN-LAST:event_mnInstituteActionPerformed

    private void mnPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPublisherActionPerformed
        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(true);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnPublisherActionPerformed

    private void mnSessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSessonActionPerformed
        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(true);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnSessonActionPerformed

    private void mnShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnShiftActionPerformed
        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(true);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnShiftActionPerformed

    private void mnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnStudentActionPerformed
        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(true);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnStudentActionPerformed

    private void mnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUserActionPerformed
        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsBookIssue().setVisible(false);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(true);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnUserActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        book = new Book(
                txtBookName.getText(),
                txtBookCode.getText(),
                comboAuthorName.getSelectedItem().toString(),
                comboPublisherName.getSelectedItem().toString(),
                comboEditionName.getSelectedItem().toString(),
                Double.parseDouble(txtxUnitPrice.getText()),
                Integer.parseInt(txtQty.getText()),
                Double.parseDouble(txtTotalPrice.getText()),
                txtRackNo.getText(),
                txtIssuNo.getText(),
                comboCategoryName.getSelectedItem().toString(),
                (comboDay.getSelectedItem().toString())+"/"+(comboMonth.getSelectedItem().toString())+"/"+(comboYear.getSelectedItem().toString())
        );

        bookService = new BookService();
        bookService.save(book);

        //for book summary
        bookSummaryService = new BookSummaryService();

        List list = bookSummaryService.getList();
        int sizeOfList = list.size();
        // if (sizeOfList == 0) {

        try {
            BookSummary bs = bookSummaryService.getBookSummaryByBookCode(txtBookCode.getText());
            //test
            //   BookSummary bsxyv = new BookSummary(txtBookCode.getText(), txtBookName.getText(), Integer.parseInt(txtQty.getText()), Integer.parseInt(txtQty.getText()), 0, 0);

            //   bookSummaryService.saveWhenBookPurchase(bsxyv);
            //test end
            if (bs != null) {
                if (bs.getBookCode().equals(txtBookCode.getText())) {

// data from db
                    int preTotalQty = bs.getTotalStock();
                    int preAvailableQty = bs.getAvilableStock();

                    // after modification
                    int nowTotalQty = bs.getTotalStock() + Integer.parseInt(txtQty.getText());
                    int nowAvailableQty = bs.getAvilableStock() + Integer.parseInt(txtQty.getText());

                    BookSummary bsx = new BookSummary(nowTotalQty, nowAvailableQty);
                    bsx.setId(bs.getId());

                    bookSummaryService.updateWhenBookPurchase(bsx);

                    refreshTable();

                } else {
                    BookSummary bsxyz = new BookSummary(txtBookCode.getText(), txtBookName.getText(), Integer.parseInt(txtQty.getText()), Integer.parseInt(txtQty.getText()), 0, 0);

                    bookSummaryService.saveWhenBookPurchase(bsxyz);

                    refreshTable();

                }
            } else {
                BookSummary bsxy = new BookSummary(txtBookCode.getText(), txtBookName.getText(), Integer.parseInt(txtQty.getText()), Integer.parseInt(txtQty.getText()), 0, 0);

                bookSummaryService.saveWhenBookPurchase(bsxy);

                refreshTable();

            }
        } catch (Exception e) {
            BookSummary bsxy = new BookSummary(txtBookCode.getText(), txtBookName.getText(), Integer.parseInt(txtQty.getText()), Integer.parseInt(txtQty.getText()), 0, 0);

            bookSummaryService.saveWhenBookPurchase(bsxy);

            refreshTable();

        }

        
        lblMsg.setText("1 record add.");
        refreshTable();

    }//GEN-LAST:event_btnAddActionPerformed

    private void tblShowBookInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblShowBookInformationMouseClicked
        // TODO add your handling code here:

        int row = tblShowBookInformation.getSelectedRow();
        TableModel tableModel = tblShowBookInformation.getModel();

        txtBookName.setText(tableModel.getValueAt(row, 1).toString());
        txtBookCode.setText(tableModel.getValueAt(row, 2).toString());
        comboAuthorName.setSelectedItem(new Object().equals(tableModel.getValueAt(row, 3).toString()));
        comboPublisherName.setSelectedItem(new Object().equals(tableModel.getValueAt(row, 4).toString()));
        comboEditionName.setSelectedItem(new Object().equals(tableModel.getValueAt(row, 5).toString()));
        txtxUnitPrice.setText(tableModel.getValueAt(row, 6).toString());
        txtQty.setText(tableModel.getValueAt(row, 7).toString());
        txtTotalPrice.setText(tableModel.getValueAt(row, 8).toString());
        txtRackNo.setText(tableModel.getValueAt(row, 9).toString());
        txtIssuNo.setText(tableModel.getValueAt(row, 10).toString());
        comboCategoryName.setSelectedItem(new Object().equals(tableModel.getValueAt(row, 11).toString()));

    }//GEN-LAST:event_tblShowBookInformationMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void mnLogout3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnLogout3MouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
        new LmsAuthor().setVisible(false);
        new LmsBookCategory().setVisible(false);
        new LmsPurchaseBook().setVisible(false);
        new LmsDashboard().setVisible(true);
        new LmsBookReceive().setVisible(false);
        new LmsBookSummary().setVisible(false);
        new LmsDepartment().setVisible(false);
        new LmsEdition().setVisible(false);
        new LmsInstitute().setVisible(false);
        new LmsPublisher().setVisible(false);
        new LmsSesson().setVisible(false);
        new LmsShift().setVisible(false);
        new LmsStudent().setVisible(false);
        new LmsUser().setVisible(false);

        new LoginForm().setVisible(false);
    }//GEN-LAST:event_mnLogout3MouseClicked

    public void displayBookWithinTable() {
        bookService = new BookService();
        List<Book> pList = bookService.getList();
        DefaultTableModel model = (DefaultTableModel) tblShowBookInformation.getModel();
        Object[] row = new Object[13];

        for (int i = 0; i < pList.size(); i++) {
            row[0] = pList.get(i).getId();
            row[1] = pList.get(i).getName();
            row[2] = pList.get(i).getBookCode();
            row[3] = pList.get(i).getAuthor();
            row[4] = pList.get(i).getPublisher();
            row[5] = pList.get(i).getEdition();
            row[6] = pList.get(i).getUnitPrice();
            row[7] = pList.get(i).getQty();
            row[8] = pList.get(i).getTotalPrice();
            row[9] = pList.get(i).getRackNo();
            row[10] = pList.get(i).getIssnNo();
            row[11] = pList.get(i).getCategory();
            row[12] = pList.get(i).getPurchaseDate();

            model.addRow(row);
        }

    }

    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblShowBookInformation.getModel();
        model.setRowCount(0);
        displayBookWithinTable();
    }

    
    public void showAuthorIdInTable(){
        
        AuthorService authorService=new AuthorService();
        
        Set<Author> authorList=authorService.getAuthorList();
        
        authorList.forEach((a) -> {
            comboAuthorName.addItem(a.getName());
        });
        
    }
    
    
    public void showPublisherInTable(){
        
        PublisherService publisherService=new PublisherService();
        
        Set<Publisher> publisherList=publisherService.getPublisherList();
        
        publisherList.forEach((p) -> {
            comboPublisherName.addItem(p.getName());
        });
        
    }
    
    
    public void showEditionInTable(){
        
        EditionService editionService=new EditionService();
        
        Set<Edition> editionsList=editionService.getEditionList();
        
        editionsList.forEach((e) -> {
            comboEditionName.addItem(e.getName());
        });

    }
    
    
    public void showCategoryInTable(){
        
        BookCategoryService bookCategoryService=new BookCategoryService();
        
        Set<BookCategory> bookCategoryList= bookCategoryService.getBookCategoryList();
        
        bookCategoryList.forEach((c) -> {
            comboCategoryName.addItem(c.getName());
        });
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LmsPurchaseBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LmsPurchaseBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LmsPurchaseBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LmsPurchaseBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LmsPurchaseBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> comboAuthorName;
    private javax.swing.JComboBox<String> comboCategoryName;
    private javax.swing.JComboBox<String> comboDay;
    private javax.swing.JComboBox<String> comboEditionName;
    private javax.swing.JComboBox<String> comboMonth;
    private javax.swing.JComboBox<String> comboPublisherName;
    private javax.swing.JComboBox<String> comboYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnAuthor;
    private javax.swing.JMenuItem mnBookCategory;
    private javax.swing.JMenuItem mnBookIssue;
    private javax.swing.JMenuItem mnBookReceive;
    private javax.swing.JMenuItem mnBookSummary;
    private javax.swing.JMenuItem mnDepartment;
    private javax.swing.JMenuItem mnEdition;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JMenuItem mnInstitute;
    private javax.swing.JMenu mnLogout;
    private javax.swing.JMenu mnLogout1;
    private javax.swing.JMenu mnLogout2;
    private javax.swing.JMenu mnLogout3;
    private javax.swing.JMenuItem mnPublisher;
    private javax.swing.JMenuItem mnPurchaseBook;
    private javax.swing.JMenuItem mnSesson;
    private javax.swing.JMenuItem mnShift;
    private javax.swing.JMenuItem mnStudent;
    private javax.swing.JMenuItem mnUser;
    private javax.swing.JTable tblShowBookInformation;
    private javax.swing.JTextField txtBookCode;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtIssuNo;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtRackNo;
    private javax.swing.JTextField txtTotalPrice;
    private javax.swing.JTextField txtxUnitPrice;
    // End of variables declaration//GEN-END:variables
}
